Decompile module 52
pret/pokediamond pull request #333
Opened 2021-03-16 17:29 UTC by remicalixte

This one looks like it's called when creating a new save file. SetAvatar and SetTrainer_ID makes me think so.

No idea what is the big byte array at the end

2021-03-16 17:37 UTC, red031000 requested changes
module 52 really should be split into its constituent files, blame me for not being fast enough on that

2021-03-16 17:37 UTC, red031000 commented on include/global.h
> +
this isn't valid, mwcc does not use \_\_attribute\_\_. if you want to use unused, do #pragma unused(var)

2021-03-16 17:42 UTC, remicalixte commented
How can I know the correct split?

2021-03-16 17:45 UTC, red031000 commented
the correct split is defined by the japanese version, the compiler used there ordered functions differently in files (last first) compared to the US version

2021-03-16 17:49 UTC, remicalixte commented
So I need to extract a japanese rom to find out the split? Is there a tool to do this?

2021-03-17 16:25 UTC, red031000 commented
don't worry about it for now, I can sort it out later

2021-03-17 16:25 UTC, red031000 approved these changes

2021-03-17 16:25 UTC, merged