Decompile start of unk_02016B94.s
pret/pokediamond pull request #349
Opened 2021-03-26 18:04 UTC by remicalixte

I managed to decompile the first few functions of this file and then spent way to much time trying to match the next function.

I has a huge switch statement and I couldn't get the right register allocations and order so I'm giving up for now. Are you still interested in my attempt? It still matches a good part of the function but not all of it as I said.

2021-03-26 18:48 UTC, red031000 commented
if you are unable to match a function you should ideally use a nonmatching (see an example in text.c) with your best guess

2021-03-27 12:29 UTC, remicalixte commented
So I tried to use the ASM_GLOBAL macro and putting the asm function in a file but the build doesn't match this way. Using `asmdiff` I can see that the asm function is injected in the binary but there is some strange padding after it that is shifting everything. I'm trying to understand what `asm_processor.py` is doing

2021-03-31 13:41 UTC, red031000 commented
if you would like to finish this file, I can merge it in

2021-03-31 17:58 UTC, remicalixte commented
I was working on the next function and it's also really hard to match. I tried adding a non-matching as well but asm_processor seems broken when there are several `GLOBAL_ASM` in one file. I'll let this file as is for now and work an easier ones. You can merge the PR now with the asm_processor fixes and the the few decompiled functions if you wish.

I will probably go back on this file one day.

2021-05-13 17:40 UTC, remicalixte commented
6000 lines left...

2021-05-20 16:43 UTC, remicalixte commented
I finally finished this file. There is a couple of `NONMATCHING` functions.

And then there is `FUN_0201974C`:
- ~2500 lines of assembly
- a stack of 0x314 bytes
- so long that it uses `bl` to branch so the disassembler split it in 3

I think it's some kind of graphics library.

2021-05-20 19:58 UTC, ProjectRevoTPP approved these changes
Let red review this though

2021-05-20 20:56 UTC, red031000 requested changes
this

2021-05-20 20:56 UTC, red031000 commented on arm9/src/unk_02016B94.c
> +            r3 += (1 << 0xa);
can this be turned into a constant?

2021-05-20 20:57 UTC, red031000 commented on arm9/src/unk_02016B94.c
> +            r3 += (1 << 0xa);
not constant a number, I'm tired

2021-05-22 07:01 UTC, remicalixte commented on arm9/src/unk_02016B94.c
> +            r3 += (1 << 0xa);
sure

2021-05-22 16:06 UTC, red031000 commented
if the conflicts could be resolved I'd be happy to merge this in

2021-05-22 17:01 UTC, remicalixte commented
I removed `window.h` during the merge. All the content of the header is actually part of the file as decompiled. I could have renamed the whole file `window.c`/`window.h` but I think it's doing much more than purely window stuff so I don't think it's fitting

2021-05-23 00:06 UTC, red031000 commented
sorry can you resolve again Kappa

2021-05-23 00:17 UTC, red031000 submitted a review, later dismissed
approve pending merge conflict resolution

2021-05-23 04:48 UTC, remicalixte commented
resolved again

2021-05-23 04:48 UTC, ProjectRevoTPP approved these changes
per red's prior approval

2021-05-23 05:28 UTC, merged