decompile unk_0206015C
pret/pokediamond pull request #367
Opened 2021-05-01 10:14 UTC by fyr3n

decomp of unk_0206015C, since it is my first contribution, let me know if I can improve things for the future, thanks.

2021-05-01 19:48 UTC, red031000 requested changes
few things to change

2021-05-01 19:48 UTC, red031000 commented on include/unk_0206015C.h
> +extern THUMB_FUNC u32   MOD06_02244DB0(u32);
externs in the .c file

2021-05-01 19:48 UTC, red031000 commented on include/unk_0206015C.h
> +#include "global.h"
it's probably somewhat better to only put the includes required by the .h in the .h, and the rest of the includes in the .c

2021-05-01 19:48 UTC, red031000 commented on arm9/src/unk_0206015C.c
> +}
newline at end

2021-05-01 19:48 UTC, red031000 commented on arm9/src/unk_0206015C.c
> +        return 1;
return TRUE

2021-05-01 19:48 UTC, red031000 commented on arm9/src/unk_0206015C.c
> +    return 0;
return FALSE

2021-05-01 19:48 UTC, red031000 commented on include/unk_0206015C.h
> +
header guards?

2021-05-01 21:10 UTC, fyr3n commented
changes done

2021-05-01 21:21 UTC, fyr3n commented
changed commit name since it wasn't explicit enough.

2021-05-02 01:35 UTC, red031000 approved these changes

2021-05-02 02:34 UTC, ProjectRevoTPP approved these changes

2021-05-02 02:34 UTC, merged