[LEAK-INFORMED] Match and document funcs in unk_02016B94.c
pret/pokediamond pull request #401
Opened 2021-06-05 15:45 UTC by PikalaxALT

At time of drafting, all but one of the funcs build to matching. Ported over additional enums, defines, and static inline routines from NitroSDK/include/nitro/gx, and renamed symbols according to how they interface with the SDK (plus some symbols corresponding to gen 3 routines).

2021-06-06 12:50 UTC, red031000 requested changes
ints need to be changed to s32s where possible

2021-06-06 12:50 UTC, red031000 commented on arm9/src/bg_window.c
> +                //_02019A00
did you run out of time here or were you just unable to match it?

2021-06-09 12:28 UTC, PikalaxALT commented
> ints need to be changed to s32s where possible

There are 37 instances of `int` in bg_window.c. At least one of them breaks matching when replaced with `s32` and I don't have the patience to dissect which one.

2021-06-10 21:42 UTC, red031000 approved these changes

2021-06-10 21:42 UTC, merged