Decomp 3 small unks
pret/pokediamond pull request #421
Opened 2021-07-01 01:54 UTC by GliMusings

2021-07-01 02:08 UTC, red031000 requested changes

2021-07-01 02:08 UTC, red031000 commented on include/unk_02064E20.h
> +void FUN_02064E20(struct UnkSavStruct80* unk0);
include the file where this struct is defined

2021-07-01 02:08 UTC, red031000 commented on include/unk_020061E8.h
> +BOOL FUN_020061E8(void (*r0)(u32, struct TextPrinter *), u32 r1, u32 r2, u32 r3);
include nitro/types.h please

2021-07-01 02:33 UTC, red031000 approved these changes

2021-07-01 02:33 UTC, merged

2021-09-05 15:29 UTC, PikalaxALT commented on arm9/src/unk_020222E8.c
> +    return 0x5 << 0x18;
This should never have been approved.