decompile unk_02008DEC.s
pret/pokediamond pull request #445
Opened 2021-08-11 22:35 UTC by remicalixte

No idea of what this is about but GF sure loves copy-pasting stuff.

2021-08-14 07:15 UTC, red031000 requested changes
a few things that seem a little bit... off

2021-08-14 07:15 UTC, red031000 commented on arm9/src/unk_02008DEC.c
> +        struct UnkStruct_02008DEC_3 *r6 = &((struct UnkStruct_02008DEC_3 *)param1->unk00)[param2];
this cast feels slightly awkward

2021-08-14 07:15 UTC, red031000 commented on arm9/src/unk_02008DEC.c
> +        struct UnkStruct_02008DEC_4 *r6 = &((struct UnkStruct_02008DEC_4 *)param1->unk00)[param2];
same with this cast

2021-08-14 07:15 UTC, red031000 commented on arm9/src/unk_02008DEC.c
> +    void *r0 = *((void *volatile *)param1);
again this feels awkward, fakematch?

2021-08-14 07:15 UTC, red031000 commented on arm9/src/unk_02008DEC.c
> +        r6 = ((struct UnkStruct_02008DEC_4 *)param0->unk00)[param1].unk08;
are you sure about these casts?

2021-08-14 11:16 UTC, remicalixte commented on arm9/src/unk_02008DEC.c
> +    void *r0 = *((void *volatile *)param1);
indeed it is

2021-08-14 11:22 UTC, remicalixte commented
About the weird casts, if you look at `FUN_02008E6C` there is an `if` where one branch does
```
        struct UnkStruct_02008DEC_3 *r6 = &((struct UnkStruct_02008DEC_3 *)param1->unk00)[param2];
```
and the other one 
```
        struct UnkStruct_02008DEC_4 *r6 = &((struct UnkStruct_02008DEC_4 *)param1->unk00)[param2];
```
The same struct field is accessed as a array to something. The array index gives us the size of the things in the array (in asm offset = index * size). This led me to create these two different structs definition because the sizes were clearly different: `sizeof(struct UnkStruct_02008DEC_3)` is 0x4C and `sizeof(struct UnkStruct_02008DEC_4)` is 0x18. If you know a better cleaner way to achieve the same result please tell me.

2021-08-14 11:24 UTC, PikalaxALT commented
> If you know a better cleaner way to achieve the same result please tell me.

Google the `union` keyword in C.

2021-08-14 11:35 UTC, remicalixte commented
I didn't think about using a `union` lol

2021-08-15 08:13 UTC, red031000 approved these changes

2021-08-15 08:13 UTC, merged