Refactor msgenc to pass keys via cli arg
pret/pokediamond pull request #459
Opened 2021-08-27 17:03 UTC by PikalaxALT

Based on discussions in the Discord.

```
msgenc v2021.08.27
Usage: msgenc [-h] [-v] -d|-e [-k KEY] -c CHARMAP INFILE OUTFILE

INFILE        Required: Path to the input file to convert (-e: plaintext; -d: binary).
OUTFILE       Required: Path to the output file (-e: binary; -d: plaintext).
-c CHARMAP    Required: Path to a text file with a character mapping, for example pokeheartgold/charmap.txt.
-d            Decode from binary to text, also print the key
-e            Encode from text to binary using the provided key
-k KEY        The 16-bit encryption key for this message bank. Default: computes it from the binary file name
-v            Print the program version and exit.
-h            Print this message and exit.
```

2021-08-30 22:14 UTC, red031000 requested changes
you can also remove *.key from the .knarcignore

2021-08-30 22:14 UTC, red031000 commented on charmap.txt
> +// Character mapping for Pokémon HeartGold and SoulSilver
thmm yes this is heartgold and soulsilver

2021-08-31 00:44 UTC, PikalaxALT commented
> you can also remove *.key from the .knarcignore

I could, but it's not required to do so.

2021-08-31 01:05 UTC, red031000 approved these changes
ok sure

2021-08-31 01:05 UTC, merged